### ISSUE TITLE
Middleware auto-imports broken by nuxt@^3.10.3

### ISSUE THREAD

**Issue by birdlavv** [nuxt-modules/hanko#112]
v3.10.3 Reproduction:
https://stackblitz.com/edit/github-6euwfp-nijjwv?file=package.json,pages%2Findex.vue,nuxt.config.ts

Error message
`[vite-node] [ERR_LOAD_URL] virtual:nuxt:#build/hanko-elements`

Downgrading to v3.10.2 fixes the issue.
https://stackblitz.com/edit/github-6euwfp?file=package.json,pages%2Findex.vue,nuxt.config.ts

The issue appears with the latest nuxt@3.11.1 release

**Comment by felix-dolderer** [comment]
Same issue for me.

Adding `ssr: false` to `nuxt.config.ts` functions as a workaround (though obviously I'd like to avoid that)

**Comment by birdlavv** [comment]
It appears to only affect the development server. I'm able to build the project and sign in without issue.
