### ISSUE TITLE
Can't run playground

### ISSUE THREAD

**Issue by nikitavoloboev** [nuxt-modules/hanko#19]
Get this

<img width="846" alt="image" src="https://github.com/nuxt-modules/hanko/assets/6391776/05a5cbeb-4ffb-48e8-a59f-c3ea5adf67e0">

I ran `pnpm i` before

<img width="835" alt="image" src="https://github.com/nuxt-modules/hanko/assets/6391776/b438bdd8-a367-4ab1-89d0-a9e854820b4b">

**Comment by danielroe** [comment]
You need to run `pnpm dev:prepare` in the root directory.
