### ISSUE TITLE
Correcting user type

### ISSUE THREAD

**Issue by rktmatt** [nuxt-modules/hanko#98]
When doing :
```JS
const hanko = useHanko();
const user = await hanko?.user.getCurrent();
```
The user type is defined as follows:
```JS
user = {
email,
id,
webauthn_credentials[]
}
```
This lacks two elements that are quite useful: `updated_at` and `created_at`

Could we add those?

Thanks!

**Comment by felix-dolderer** [comment]
The `hanko.user.getCurrent()` function comes directly from Hanko and their frontend SDK (https://teamhanko.github.io/hanko/jsdoc/hanko-frontend-sdk).

The function returns a User according to their interface/DTO as defined here: https://teamhanko.github.io/hanko/jsdoc/hanko-frontend-sdk/User.html

If you want this to be changed, you should open an issue directly on their repo: https://github.com/teamhanko/hanko/issues
